
server:
  port: 9090
  
#
#management:
#  endpoints:
#    web:
#    exposure:
#      include = *
#    enabled-by-default: false
#  endpoint:
#    info:
#      enabled: true


#spring:
#  security:
#    user:
#      name: admin
#      password: admin


spring:
  data:
    mongodb:
      database: drugs_db


#192.76.45.12

#      uri: 
     